In [61]:
import numpy as np
import chainer
from chainer import cuda, Function, \
        report, training, utils, Variable
from chainer import datasets, iterators, optimizers, serializers
from chainer import Link, Chain, ChainList
import chainer.functions as F
import chainer.links as L
from chainer.training import extensions

### <font color='blue'>変数と偏微分のやり方</font>

In [67]:
x1 = Variable(np.array([1]).astype(np.float32))
x2 = Variable(np.array([2]).astype(np.float32))
x3 = Variable(np.array([3]).astype(np.float32))

In [68]:
z = (x1-2*x2-1)**2 + (x2*x3 - 1)**2 + 1

In [69]:
z.data

array([ 42.], dtype=float32)

In [72]:
z.backward()

In [73]:
x1.grad

array([-8.], dtype=float32)

In [74]:
x2.grad

array([ 46.], dtype=float32)

In [75]:
x3.grad

array([ 20.], dtype=float32)

### <font color='blue'>sin, sigmoid関数</font>

In [76]:
x = Variable(np.array([-1], dtype=np.float32))

In [77]:
F.sin(x).data # sin関数

array([-0.84147096], dtype=float32)

In [78]:
F.sigmoid(x).data # sigmoid関数

array([ 0.2689414], dtype=float32)

### <font color='blue'>cos関数とsin関数で微分の確認</font>

In [79]:
x = Variable(np.array([-0.5], dtype=np.float32))

In [80]:
z = F.cos(x)

In [81]:
z.data

array([ 0.87758255], dtype=float32)

In [82]:
z.backward()

In [83]:
x.grad

array([ 0.47942555], dtype=float32)

In [84]:
((-1) * F.sin(x)).data

array([ 0.47942555], dtype=float32)

### <font color='blue'>変数が多次元</font>

In [107]:
x = Variable(np.array([-1, 0, 1], dtype=np.float32))

In [108]:
z = F.sin(x)

In [109]:
z.grad = np.ones(3, dtype=np.float32)

In [110]:
z.backward()

In [111]:
x.grad

array([ 0.54030228,  1.        ,  0.54030228], dtype=float32)

### <font color='blue'>links</font>

自分が考えたモデルをlinksとfunctionで、単純に組み合わせることができたら<br>
それで、Chainerのプログラムは完成である。<br>

### <font color='blue'>重みとバイアス</font>

l層の入力が３次元、l+1層の次元が４次元となっている。

In [112]:
h = L.Linear(3, 4)

In [114]:
h.W.data

array([[ 0.20599855,  0.28891426,  0.85841626],
       [ 0.05860077, -0.98470169, -0.18270016],
       [ 0.26682687,  0.06179291,  0.51657456],
       [ 0.03036615, -0.42421719,  0.56493181]], dtype=float32)

In [115]:
h.b.data

array([ 0.,  0.,  0.,  0.], dtype=float32)